# SPDX-PackageName: turku-api
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://forge.colobox.com/rfinnie/turku-api
# SPDX-FileCopyrightText: © 2026 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: AGPL-3.0-or-later
---
when:
  - event: ["push", "pull_request", "manual"]
labels:
  platform: "linux/amd64"
  pool: "snowman"
clone:
  git:
    image: "docker.io/woodpeckerci/plugin-git:latest@sha256:ebde4a4d07e0e24b630082484d192890dd4f6d442d90bf5466f0763860f83652"  # 2026-05-28
steps:
  - name: "Docker build"
    image: "docker.io/library/docker:cli@sha256:873de13208aab9c1de73fe984fd45883e01464fcfcc85efa20aa56a9ccfe7aa6"  # 2026-06-04
    commands: |
      set -x
      IMAGE_NAME="$(echo "$${CI_REPO}" | tr '[:upper:]' '[:lower:]')"
      IMAGE_TAG="$${CI_WORKFLOW_NAME}-$(echo "$${CI_SYSTEM_PLATFORM}" | sed 's,/,-,g')"
      IMAGE_ID="build/$${IMAGE_NAME}:$${IMAGE_TAG}"
      echo "Building: $${IMAGE_ID}"
      docker image build -t "$${IMAGE_ID}" .
      docker run --rm "$${IMAGE_ID}" django-admin check
      docker run --rm "$${IMAGE_ID}" django-admin test
  - name: "Notify Mastodon if failure"
    when:
      - status: ["failure"]
    image: "docker.io/woodpeckerci/plugin-mastodon-post:latest@sha256:456597681cff794b6ddb7b085ce95c42a18301e512503898c4abdaa1080e7e4c"  # 2026-04-19
    settings:
      server_url: "https://m29.us"
      access_token:
        from_secret: "m29_token"
      status: |
        🪿 🪿 🪿 FAILURE: {{ CI_REPO }} 🪿 🪿 🪿
        Workflow: {{ CI_WORKFLOW_NAME }} ({{ CI_PIPELINE_EVENT }} on {{ CI_COMMIT_REF }})

        Pipeline: {{ CI_PIPELINE_URL }}
        Commit: {{ CI_PIPELINE_FORGE_URL }}
